app/views/analysis_views.py
from flask import Blueprint, url_for, render_template, g
from werkzeug.utils import redirect

from app import db
from app.models import Survey

bp = Blueprint('analysis', __name__, url_prefix='/record')


@bp.route('/analysis')
def analysis():
    if g.user:
        surveydb_list = Survey.query.order_by(Survey.create_date)
        survey_list = []
        for survey in surveydb_list:
            if survey.user_id == g.user.id:
                hour = str(survey.create_date.hour)
                min = str(survey.create_date.minute)
                if len(hour) == 1:
                    hour = '0' + str(survey.create_date.hour)
                if len(min) == 1:
                    min = '0' + str(survey.create_date.minute)
                date = str(survey.create_date.year) + '/' + str(survey.create_date.month) + '/' \
                    + str(survey.create_date.day) + ' ' + hour + ':' + min
                survey_list.append([survey.score, date])

        print(date)

        return render_template('analysis.html', survey_list = survey_list, g_user = g.user)
    else:
        return redirect(url_for('main.home'))

app/views/auth_views.py
from datetime import datetime

from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash
from werkzeug.utils import redirect

from app import db
from app.forms import UserCreateForm
from app.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        tel=form.tel.data, email=form.email.data,
                        create_date = datetime.now())
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('signup.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

app/views/record_views.py
from flask import Blueprint, render_template, url_for, g
from werkzeug.utils import redirect

from numpy import dot
from numpy.linalg import norm
import os

from app import db
from app.models import Question, Answer
from app.load_model import model, train_data
from datetime import datetime

# from gtts import gTTS
from app.vocoding.waveglow.tacotron2.inference_1 import synthesizer
from scipy.io.wavfile import write
import ftplib

from flask_socketio import send, emit
from app import socket_io

from pydub import AudioSegment


# ftp 정보
host = '192.168.3.46'
user = 'voco-test1'
passwd = 'etevers1123!!'

def cos_sim(A, B):
    return dot(A, B)/(norm(A)*norm(B))

def return_similar_answer(input):
    embedding = model.encode(input)
    train_data['score'] = train_data.apply(lambda x: cos_sim(x['embedding'], embedding), axis=1)
    return train_data.loc[train_data['score'].idxmax()]['A']

bp = Blueprint('record', __name__, url_prefix='/record')

@bp.route('/')
def record():
    if g.user:
        question_list = Question.query.order_by(Question.create_date)

        return render_template('record.html',
        question_list=question_list, 
        g_user = g.user)
    else:
        return redirect(url_for('main.home'))


@socket_io.on("message")
def request(message):
    print("message : ", message)
    to_client = dict()
    if not message == 'new_connect':

        question = Question.query.filter_by(id = message)
        question = question[0]

        contents = question.contents
        hour = str(question.create_date.hour)
        min = str(question.create_date.minute)
        if len(hour) == 1:
            hour = '0'+hour
        if len(min) == 1:
            min = '0'+min
        
        time = hour + ':' + min

        to_client['message'] = contents
        to_client['type'] = 'question'
        to_client['time'] = time
        send(to_client, broadcast = True)

        if not question.answer_set:
            answer = Answer(question = question,
                        contents=return_similar_answer(contents),
                        create_date = datetime.now())
            db.session.add(answer)
            db.session.commit()
        contents = answer.contents
        hour = str(answer.create_date.hour)
        min = str(answer.create_date.minute)
        if len(hour) == 1:
            hour = '0'+hour
        if len(min) == 1:
            min = '0'+min
        
        time = hour + ':' + min

        to_client['message'] = contents
        to_client['type'] = 'answer'
        to_client['time'] = time
        send(to_client, broadcast = True)

        if not answer.ftp_address:
            file_name = 'test_' + str(answer.question_id) + '.wav'
            # tts = gTTS(
            #     text = answer.contents,
            #     lang = 'ko', slow = False
            # )
            # tts.save(file_name)
            audio, sampling_rate = synthesizer.inference(answer.contents)
            write(file_name, sampling_rate, audio)

            # files                                                                         
            file_name_mp3 = 'test_' + str(answer.question_id) + '.mp3'
            

            # convert wav to mp3                                                            
            sound = AudioSegment.from_wav(file_name)
            sound.export(file_name_mp3, format="mp3")

            try:
                # ftp 연결
                with ftplib.FTP() as ftp:
                    ftp.connect(host=host,port=21)
                    ftp.encoding = 'utf-8'
                    ftp.login(user=user,passwd=passwd)
                
                    ftp.cwd('/home')  # 현재 폴더 이동
                
                    # 파일업로드
                    with open(file=file_name_mp3, mode='rb') as wf:
                        ftp.storbinary('STOR '+file_name_mp3, wf)
                
                    # print(ftp.dir())
                    # print('업로드 완료')
                
            except Exception as e:
                print(e)
            
            else:
                answer.ftp_address = file_name
                db.session.commit()
                # print('db 기록 완료')
                #파일 삭제
                if os.path.exists(file_name):
                    os.remove(file_name)
                if os.path.exists(file_name_mp3):
                    os.remove(file_name)

    emit('response', '응답 완료')

app/templates/analysis.html
{% extends 'base.html' %}
{% block content %}
<body style="background-color: #a9cbd7;" >
    {% set view = namespace(value=False) %}
    {% if survey_list %}
        <p style="font-size: 30px; text-align: center; padding-top: 15%">최근 설문 일자는 {{survey_list[-1][1]}} 입니다.
            <br> 이날의 점수는 {{ survey_list[-1][0] }}점 입니다</p>
        {% if survey_list[-1][0] <= 10 %}
            <p style="font-size: 30px; text-align: center;">우울증 징후가 발견되지 않았습니다</p>
        {% else %}
            <p style="font-size: 30px; text-align: center;">우울증 의심 상태입니다</p>
        {% endif %}
        <div id="linechart" style="margin: 0px 100px;"></div>
    {% else %}
        <p style="font-size: 50px; text-align: center; line-height: 50vh">기록이 없습니다.</p>
    {% endif %}

    <script>
        var survey_list = {{ survey_list|tojson }};
        var axis_x = ['x']
        var axis_y = [{{ g_user.username|tojson }}]

        for (var value of survey_list){
            axis_y.push(value[0]);
            axis_x.push(value[1]);
        }

        var chart = c3.generate({
            bindto: "#linechart",
            data: {
                x: 'x',
                xFormat: '%Y/%m/%d %H:%M',
                columns: [
                    axis_x,
                    axis_y
                ]
            },
            axis: {
                x: {
                    label: {
                        text: 'Date'
                    },
                    type : 'category',
			        tick: {
                        rotate: 30,
					    format: '%Y-%m-%d %H:%M'
			        }
                },
                y: {
                    beginAtZero: true,
                    max: 15,
                    stepSize : 1,
                    // min: 1,
                    label: { // ADD
                        text: 'Score'
                    }
                }
            }
        });
    </script>
</body>

{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <title>Hello</title>
        <!-- 소켓통신 -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.1.2/socket.io.min.js"></script>
        <!-- c3 차트 플러그인 -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.css"/>
        <script src="https://d3js.org/d3.v3.min.js"></script>     
        <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js"></script>
        <!-- 구글 아이콘 -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
        <script type="text/javascript">
            var check1 = true;
            var check2 = true;
            $(document).ready(function(){
                $("#nav ul.sub2").hide();
                let chat = document.querySelector('.contents1');
                    chat.scrollTop = chat.scrollHeight

                $("#nav ul li ul").click(function(){
                    check1 = false;
                    check2 = false;
                    $("#nav ul.menu1").click(function(){
                        check1 = true;
                        check2 = true;
                    });
                    $("#nav ul.menu2").click(function(){
                        check1 = true;
                        check2 = true;
                    });
                });
                $("#nav ul.menu1").click(function(){
                    if(check1){
                        $("ul li ul.sub1").slideToggle("slow");
                    }
                });
                $("#nav ul.menu2").click(function(){
                    if(check2){
                        $("ul li ul.sub2").slideToggle("slow");
                    }
                });   
            });
        </script>
    </head>
    <body class="fade">
        <script type="text/javascript">
            $(document).ready(function(){
                // console.log('http://' + document.domain + ':' + location.port)
                var socket = io.connect('http://' + document.domain + ':' + location.port);
        
                socket.on('connect', function(){
                        var connect_string = 'new_connect';
                        socket.send(connect_string);
                });
        
                socket.on('message', function(msg){
                        // console.log(type(msg));
                        if(msg.type === 'question'){
                            $('#messages').append('<div class="chat ch2"> \
                                <div class="icon"><img class="profile" src="{{ url_for("static", filename="img/profile.jpg") }}"></div> \
                                <div class="textbox">'+ msg.message +'</div> \
                                <div class="date">'+ msg.time +'</div>'
                                )
                        } else if(msg.type === 'answer'){
                            $('#messages').append('<div class="chat ch1"> \
                                <div class="icon"><img class="profile" src="{{ url_for("static", filename="img/profile.jpg") }}"></div> \
                                <div class="textbox">'+ msg.message +'</div> \
                                <div class="date">'+ msg.time +'</div>'
                                )
                        }
                        // console.log('Received Message : '+msg.type);
                        let chat = document.querySelector('.contents1');
                        chat.scrollTop = chat.scrollHeight
                });
            });
        </script>
        <div id="wrapper">
            <!-- 네비게이션바 -->
            {% include "navbar.html" %}
            <!-- 기본 템플릿 안에 삽입될 내용 Start -->
            {% block content %}
            {% endblock %}
            <!-- 기본 템플릿 안에 삽입될 내용 End -->
        </div>
        
        <!-- {% include "footer.html" %} -->
        <!-- Bootstrap JS -->
        <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='script.js') }}"></script>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
              window.setTimeout(() => {
                document.body.classList.remove('fade');
              });
            });
        </script>
    </body>
</html>

app/templates/footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row justify-content-md-center">
            내용
        </div>
    </div>
    
</footer>

app/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="row justify-content-center">
    <div class="col-md-auto">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="row justify-content-center">
    <div class="col-md-auto">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>
{% endfor %}

app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div id="center">
    <div class="profile_box" style="background: #BDBDBD;">
        <img class="profile" src="{{ url_for('static', filename='img/profile.jpg') }}">
    </div>
    <body style="background-color: #a9cbd7;" >
        <div class="container-fluid">
            <form class="row justify-content-md-center" method="post">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                <div class="row justify-content-md-center">
                    <div class="col-md-auto">
                        <label for="username" class="visually-hidden">ID</label>
                        <input type="text" class="form-control" name="username" id="username" value="{{ form.username.data or '' }}" placeholder="ID">
                    </div>
                </div>
                <div class="row">
                    <div class="col-1">
                        <label></label>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-md-auto">
                        <label for="password" class="visually-hidden">PW</label>
                        <input type="password" class="form-control" name="password" id="password" value="{{ form.username.data or '' }}" placeholder="PW">
                    </div>
                </div>
                <div class="row">
                    <div class="col-1">
                        <label></label>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-md-auto">
                        <a href="{{ url_for('auth.signup') }}">회원가입</a>
                    </div>
                    <div class="col-md-1">
                        <label></label>
                    </div>
                    <div class="col-md-auto">
                        <button type="submit" class="btn btn-primary">로그인</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-1">
                        <label></label>
                    </div>
                </div>
            </form>
        </div>
    </body>
</div>

{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">DoL</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>

app/templates/recode.html
{% extends 'base.html' %}
{% block content %}
<!-- 메인 영역 -->
<div class="container1" style='background-color: #a9cbd7' >
    {% set date_list = [] %}
    <!-- 컨텐츠 영역 -->
    <div class="contents1">
        <body>
            {% set view = namespace(value=False) %}
            {% set check_date = namespace(year=0, month=0, day=0) %}
            <div class="wrap">
                {% if question_list %}
                    {% for question in question_list %}
                        {% if question.user_id == g_user.id %}
                        {% set view.value = True %}
                        {% set date = namespace(year=question.create_date.year, month=question.create_date.month, day=question.create_date.day) %}
                            {% if date.day != check_date.day %}
                                {% set check_date.year = date.year %}
                                {% set check_date.month = date.month %}
                                {% set check_date.day = date.day %}
                                {{ date_list.append(date.year|string+'년 '+date.month|string+'월 '+date.day|string+'일') or "" }}
                                <a name="{{date_list[-1]}}" style="padding: 30px 20px 0 20px"></a>
                                <p style="text-align: center; margin: 0;">{{date_list[-1]}}</p>
                                <hr style="margin: 0; width : 95%;">
                            {% endif %}
                            <div class="chat ch2">
                                <div class="icon"><i class="fa-solid fa-user"></i></div>
                                <div class="textbox">{{ question.contents }}</div>
                                <div class="date">{{ question.create_date.hour }}:{{ question.create_date.minute }}</div>
                            </div>
                            {% if question.answer_set %}
                                <div class="chat ch1">
                                    <div class="icon"><i class="fa-solid fa-user"></i></div>
                                    <div class="textbox">{{ question.answer_set[0].contents }}</div>
                                    <div class="date">{{ question.create_date.hour }}:{{ question.create_date.minute }}</div>
                                </div>
                            {% endif %}
                        {% endif %} 
                    {% endfor %}
                    {% if not view.value %}
                        <p style="font-size: 50px; text-align: center; line-height: 50vh">기록이 없습니다.</p>
                    {% endif %}
                {% endif %}
            </div>
        </body>
    </div>

    <!-- 사이드바 영역 -->
    <div class="sidebar1" style="overflow-y: scroll; font-size: larger;">
        <!-- 메뉴 상태 변경 버튼 추가 -->
        <label class="toggle1">
            <span></span>
            <span></span>
            <span></span>
        </label>
        <div id="nav">
            <ul class="menu">
                <li><a href="#">MENU 1</a>
                    <ul class="sub">
                        {% if date_list %}
                            {% for dates in date_list %}
                            <li><a href="#{{dates}}">{{dates}}</a></li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
        
    </div>
  
</div>
<script src="{{ url_for('static', filename='menu.js') }}"></script>
{% endblock %}

app/templates/record.html
{% extends 'base.html' %}
{% block content %}
<!-- 메인 영역 -->
<div class="container1" style='background-color: #a9cbd7' >
    {% set date_list = [] %}
    <!-- 컨텐츠 영역 -->
    <div class="contents1">
        <body>
            {% set view = namespace(value=False) %}
            {% set check_date = namespace(year=0, month=0, day=0) %}
            <div class="wrap" id="reload">
                {% if question_list %}
                    {% for question in question_list %}
                        {% if question.user_id == g_user.id %}
                        {% set view.value = True %}
                        {% set date = namespace(year=question.create_date.year, month=question.create_date.month, day=question.create_date.day) %}
                            {% if date.day != check_date.day %}
                                {% set check_date.year = date.year %}
                                {% set check_date.month = date.month %}
                                {% set check_date.day = date.day %}
                                {{ date_list.append(date.year|string+'년 '+date.month|string+'월 '+date.day|string+'일') or "" }}
                                <a name="{{date_list[-1]}}" style="padding: 10px"></a>
                                <p style="text-align: center; margin: 0;">{{date_list[-1]}}</p>
                                <hr style="margin: 0; width : 95%;">
                            {% endif %}
                            <div class="chat ch2">
                                <div class="icon"><img class="profile" src="{{ url_for('static', filename='img/profile.jpg') }}"></div>
                                <div class="textbox">{{ question.contents }}</div>
                                {% if question.create_date.hour | string | length == 1 %}
                                    {% if question.create_date.minute | string | length == 1 %}
                                        <div class="date">0{{ question.create_date.hour }}:0{{ question.create_date.minute }}</div>
                                    {% else %}
                                        <div class="date">0{{ question.create_date.hour }}:{{ question.create_date.minute }}</div>
                                    {% endif %}
                                {% else %}
                                    {% if question.create_date.minute | string | length == 1 %}
                                        <div class="date">{{ question.create_date.hour }}:0{{ question.create_date.minute }}</div>
                                    {% else %}
                                        <div class="date">{{ question.create_date.hour }}:{{ question.create_date.minute }}</div>
                                    {% endif %}
                                {% endif %}
                            </div>
                            {% if question.answer_set %}
                                <div class="chat ch1">
                                    <div class="icon"><img class="profile" src="{{ url_for('static', filename='img/profile.jpg') }}"></div>
                                    <div class="textbox">{{ question.answer_set[0].contents }}</div>
                                    {% if question.answer_set[0].create_date.hour | string | length == 1 %}
                                        {% if question.answer_set[0].create_date.minute | string | length == 1 %}
                                            <div class="date">0{{ question.answer_set[0].create_date.hour }}:0{{ question.answer_set[0].create_date.minute }}</div>
                                        {% else %}
                                            <div class="date">0{{ question.answer_set[0].create_date.hour }}:{{ question.answer_set[0].create_date.minute }}</div>
                                        {% endif %}
                                    {% else %}
                                        {% if question.answer_set[0].create_date.minute | string | length == 1 %}
                                            <div class="date">{{ question.answer_set[0].create_date.hour }}:0{{ question.answer_set[0].create_date.minute }}</div>
                                        {% else %}
                                            <div class="date">{{ question.answer_set[0].create_date.hour }}:{{ question.answer_set[0].create_date.minute }}</div>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            {% endif %}
                        {% endif %} 
                    {% endfor %}
                    <ul style="margin: 0; padding: 0;" id="messages"></ul>
                    {% if not view.value %}
                        <p style="font-size: 50px; text-align: center; line-height: 50vh">기록이 없습니다.</p>
                    {% endif %}
                {% endif %}
            </div>
        </body>
    </div>

    <!-- 사이드바 영역 -->
    <div class="sidebar1" style="overflow-y: scroll; font-size: larger;">
        <!-- 메뉴 상태 변경 버튼 추가 -->
        <label class="toggle1">
            <span></span>
            <span></span>
            <span></span>
        </label>
        <div id="nav">
            <ul class="menu1">
                <li>
                    <a href="#"> 
                        <div class="profile_box_small" style="background: #BDBDBD;">
                            <img class="profile_small" src="{{ url_for('static', filename='img/profile.jpg') }}">
                            
                        </div>   
                        <p style="margin:0;">{{ g_user.username }}</p>                 
                    </a>
                    <ul class="sub1">
                        {% if date_list %}
                            {% for dates in date_list %}
                                <li><a href="#{{dates}}">{{dates}}</a></li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <ul class="menu2">
                <li>
                    <a href="#"> 
                        <p style="margin:0;">메뉴</p>                 
                    </a>
                    <ul class="sub2">
                        <li><a href="{{ url_for('analysis.analysis') }}">분석</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='menu.js') }}"></script>

{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">계정생성</h5>
    <form method="post">
        {{ form.csrf_token }}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="tel">연락처</label>
            <input type="text" class="form-control" name="tel" id="tel" maxlength="11" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');"
                   value="{{ form.tel.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.data or '' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}